### ISSUE TITLE
Create a SelectID hook

### ISSUE THREAD

**Issue by xXBJXx** [AlCalzone/iobroker-react#1]
please create a SelectID Hook like here [SelectID](https://github.com/ioBroker/adapter-react/#selectidjs)

**Comment by AlCalzone** [comment]
fixed on master :)
Usage example here: https://alcalzone.github.io/iobroker-react/#/hooks/useDialogs?id=example-4-let-the-user-select-an-id-and-show-the-selected-id-and-its-state
